### ISSUE TITLE
PEN-1100.12 - As a pool owner/user I need to be able to view all notifications. (unable to get notify on SHOMNU, _57A7 PARTY is not having all the messages here)

### ISSUE THREAD

**Issue by acarnagey** [gryz/THW-Update-Needed#15]
edslack [5:14 PM]  
you taking about SetListParams for a STATUS.SHOMNU ‘OFF ?

adam [5:17 PM]  
yeah on fm qa1 i’ll do a {"command":"SETPARAMLIST","objectList":[{"objnam":"t407F","params":{"SHOMNU":"OFF"}}]} or {"command":"SETPARAMLIST","objectList":[{"objnam":"t407F","params":{"SHOMNU”:"ON"}}]} to hide or show it, it 200’s with response ok, but I'll get a {"command": "NotifyList", "messageID": "1fa4c587-365f-477d-9667-a00b6a67136a","objectList": [{ "objnam": "t407F","params": {"PARTY":"946704624 946704613 946704602 946704591 946704580 946704569 946704558 946704547"}}]} when I need the SHOMNU parameter instead.

edslack [5:21 PM]  
ok let me test here on the same QA1

adam [5:28 PM]  
also _57A7 PARTY does not match up with getActiveStatusMessages
{"command": "NotifyList","messageID": "a27eaa91-a499-4f88-b1de-614aa0456882","objectList": [{"objnam": "_57A7","params": {"PARTY": "t407F tD5CD"}}]} and {"answer":[{"objnam":"t407F","params":{"OBJTYP":"STATUS","PARENT":"I93D4","MODE":"1","SNAME":"Communication Lost","COUNT":"230","PARTY":"946705267 946705256 946705245 946705233 946705222 946705211 946705200 946705189","SINDEX":"37234","TIME":"946705267","SHOMNU":"OFF"}},{"objnam":"tD5CD","params":{"OBJTYP":"STATUS","PARENT":"ID5C7","MODE":"1","SNAME":"Communication Lost","COUNT":"14","PARTY":"946705256 946705232 946705208 946705184 946705160 946705136 946705112 946705088","SINDEX":"37234","TIME":"946705256","SHOMNU":"OFF"}},{"objnam":"t86C9","params":{"OBJTYP":"STATUS","PARENT":"ID5C7","MODE":"0","SNAME":"pH at Feed Limit","COUNT":"2","PARTY":"947936342 947935734","SINDEX":"52372","TIME":"947936342","SHOMNU":"OFF"}},{"objnam":"tFCD8","params":{"OBJTYP":"STATUS","PARENT":"ID5C7","MODE":"0","SNAME":"ORP Too Low","COUNT":"2","PARTY":"947936342 947935734","SINDEX":"50168","TIME":"947936342","SHOMNU":"OFF"}},{"objnam":"t407F","params":{"OBJTYP":"STATUS","PARENT":"I93D4","MODE":"1","SNAME":"Communication Lost","COUNT":"230","PARTY":"946705267 946705256 946705245 946705233 946705222 946705211 946705200 946705189","SINDEX":"37234","TIME":"946705267","SHOMNU":"OFF"}},{"objnam":"tD5CD","params":{"OBJTYP":"STATUS","PARENT":"ID5C7","MODE":"1","SNAME":"Communication Lost","COUNT":"14","PARTY":"946705256 946705232 946705208 946705184 946705160 946705136 946705112 946705088","SINDEX":"37234","TIME":"946705256","SHOMNU":"OFF"}}],"queryName":"GetActiveStatusMessages","command":"SendQuery","messageID":"99b0592b-9431-4ae1-936e-691cf317dc2c","response":"200"}

[5:30]  
we get t86C9 and tFCD8 which were not mentioned in _57A7 party.

**Comment by gryz** [comment]
Update on this please?

**Comment by edgardoatpentair** [comment]
this issue has been resolved on Monday 7/18/16.

**Comment by acarnagey** [comment]
The 1st one looks fixed (showmnu on notify), but the 2nd one is still off (_57A7 party inconsistency with allActiveStatusMessages)

{"objectList":[{"objnam":"UFFFE","params":{"ENABLE":"OFF","OBJTYP":"PERMIT","PASSWRD":"0000","SHOMNU":"vogqkwzactrefluphmnbxiS"}},{"objnam":"_57A7","params":{**"PARTY":"t181D t2EC9 t7F0C"**}}],"command":"NotifyList","messageID":"4c408304-3eb8-4683-baf4-f8a0067ca649","response":"200","timeNow":"946875194","timeSince":"946874819"}

{"answer": [{**"objnam": "t181D",
       }, {"objnam": "t2EC9",
	}, {objnam": "t7F0C",
	}, {"objnam": "t181D",
	}, {"objnam": "t2EC9",
	}, {"objnam": "t7F0C",
	}, {"objnam": "t0188",**}],
	"queryName": "GetActiveStatusMessages",
	"command": "SendQuery",
	"messageID": "dde4bf95-21da-4d26-b7d6-f54bcf62c044",
	"response": "200"
}

**Comment by acarnagey** [comment]
This still is off for me either 57A7 won't have anything or it will end up have less then getActiveStatusMessages
e.g. on qa2 {
    "command": "NotifyList",
    "messageID": "98122122-7d8c-44e4-8167-7b6dc707bc33",
    "objectList": [
        {
            "objnam": "_57A7",
            "params": {
                "PARTY": ""
            }
        }
    ]
}

{"answer":[{"objnam":"t546D","params":{"OBJTYP":"STATUS","PARENT":"I1065","MODE":"0","SNAME":"pH Too Low","COUNT":"10","PARTY":"946783058 4196892922 4196875896 4196875559 1041115799 1041115799 946781795 946777287","SINDEX":"52488","TIME":"946783058","SHOMNU":"OFF"}},{"objnam":"tA2F6","params":{"OBJTYP":"STATUS","PARENT":"I1B18","MODE":"1","SNAME":"Communication Lost","COUNT":"18","PARTY":"946785359 946785348 946785337 946785326 946785315 946785304 946785293 946785282","SINDEX":"37234","TIME":"946785359","SHOMNU":"OFF"}},{"objnam":"tB3AA","params":{"OBJTYP":"STATUS","PARENT":"I1065","MODE":"1","SNAME":"Communication Lost","COUNT":"4","PARTY":"4196892902 4196892878 4196892854 4196892830","SINDEX":"37234","TIME":"4196892902","SHOMNU":"OFF"}}],"queryName":"GetActiveStatusMessages","command":"SendQuery","messageID":"d6856287-c47c-4ff4-96e3-5d0fcb37d419","response":"200"}

**Comment by acarnagey** [comment]
Right, the notifications should be working right now since we call getActiveStatusMessages on installation connection.  However, I am not 100% sure _57A7 would always work as intended and have new notifications show up in PARTY whenever they get triggered, if they don't then that would be an issue, I think this is the case.

**Comment by klewis77** [comment]
This just means we may miss a message which is an issue but should not hold up development on Pathfinders side as stated previously.

**Comment by gryz** [comment]
If I'm reading this correctly, it's still broken but is intermittent in nature.

**Comment by acarnagey** [comment]
this is still an issue, it doesn't show up in PARTY for _57A7, you have to reload the page and use the getActiveStatusMessages to get the new notification to show up
![screen shot 2016-09-12 at 3 20 46 pm](https://cloud.githubusercontent.com/assets/1028600/18451464/ad9a783c-78fc-11e6-849c-d5105c684d33.png)
